name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        compiler: clang

    - name: Install Clang-Tidy
      run: sudo apt-get install -y clang-tidy

    - name: Run Clang-Tidy
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
        cd ..
        clang-tidy -p build $(find . -name '*.cpp')
